version: '3'

services:
  nginx:
    container_name: skpi-nginx
    build:
      context: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
  php:
    container_name: skpi-php
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    user: bimantara
    volumes:
      - ./:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
  mongodb:
    container_name: skpi-mongodb
    build:
      context: ./docker/mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: toko_buku
